In [6]:
import pandas as pd

df =  pd.read_excel('Movies_Dataset.xlsx')
df

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1     Sci-Fi          2000          6.0  1680.53
1       Movie 2  Adventure          2000          2.2   987.24
2       Movie 3    Romance          2002          5.2  1122.13
3       Movie 4    Romance          2001          4.5   581.84
4       Movie 5     Action          2012          6.6  1205.51
..          ...        ...           ...          ...      ...
995   Movie 996     Sci-Fi          2013          8.7   456.39
996   Movie 997  Adventure          1993          6.2  1255.27
997   Movie 998    Fantasy          2016          8.1  1161.96
998   Movie 999     Action          1996          8.9   941.67
999  Movie 1000     Horror          1995          9.4  1390.70

[1000 rows x 5 columns]

In [21]:
# 11. Rank movies based on IMDb rating. 

df['Rank'] = df['IMDb_Rating'].rank( ascending = False, method = 'dense')
df = df.sort_values('Rank')
df

    Movie Name      Genre  Release_Year  IMDb_Rating  Revenue  Rank
564  Movie 565     Action          2020         10.0   943.50   1.0
472  Movie 473    Fantasy          1985         10.0   845.18   1.0
628  Movie 629    Mystery          1994         10.0   644.31   1.0
610  Movie 611    Mystery          2017         10.0  1355.06   1.0
241  Movie 242     Comedy          2006         10.0   802.61   1.0
..         ...        ...           ...          ...      ...   ...
80    Movie 81  Adventure          2002          1.0  1759.50  91.0
758  Movie 759     Horror          2000          1.0  1590.35  91.0
955  Movie 956  Adventure          2019          1.0  1048.85  91.0
297  Movie 298     Comedy          2006          1.0   692.08  91.0
699  Movie 700   Thriller          1984          1.0     9.60  91.0

[1000 rows x 6 columns]

In [76]:
# 12. Sort movies by release year in descending order.
df = df.sort_values('Release_Year')
df

    Movie Name            Genre  Release_Year  IMDb_Rating  Revenue  Rank
157  Movie 158          Mystery          1980          9.8   178.76   3.0
41    Movie 42         Thriller          1980          1.9  1882.34  82.0
947  Movie 948           Horror          1980          4.0   439.58  61.0
324  Movie 325            Drama          1980          3.8  1751.55  63.0
337  Movie 338          Romance          1980          7.2  1647.74  29.0
..         ...              ...           ...          ...      ...   ...
108  Movie 109          Mystery          2024          1.7  1937.74  84.0
211  Movie 212           Comedy          2024          1.5   837.32  86.0
153  Movie 154            Drama          2024          1.4  1308.61  87.0
776  Movie 777  Science Fiction          2024          1.3   558.23  88.0
178  Movie 179           Horror          2024          1.4  1178.07  87.0

[992 rows x 6 columns]

In [31]:
# 13. Find all duplicate movie names (if any).
# df.value_counts(df.duplicated('Movie Name'))
df[df.duplicated('Movie Name')]

   Movie Name      Genre  Release_Year  IMDb_Rating  Revenue  Rank
24   Movie 20    Fantasy          1982          6.9  1598.08  32.0
18   Movie 19     Comedy          1986          6.0  1783.44  41.0
14   Movie 12     Sci-Fi          1988          3.0  1134.01  71.0
12   Movie 10      Drama          1996          3.2  1352.66  69.0
22   Movie 18  Adventure          1998          7.9  1426.73  22.0
10   Movie 11    Mystery          2003          6.3   596.43  38.0
15   Movie 16     Comedy          2006          2.3  1322.79  78.0
21   Movie 17     Horror          2007          6.2  1114.31  39.0

In [47]:
# 14. Remove duplicate movie names. 

[df.duplicated(['Movie Name'])]
df=df.drop_duplicates(subset ='Movie Name')
print(df.value_counts(df.duplicated('Movie Name')))
print(df[df.duplicated(subset='Movie Name')])

False    992
Name: count, dtype: int64
Empty DataFrame
Columns: [Movie Name, Genre, Release_Year, IMDb_Rating, Revenue, Rank]
Index: []

In [63]:
# 15. Replace "Sci-Fi" genre with "Science Fiction".

print(df['Genre'].head(20).to_list())

# df = df.replace({'Genre' : { 'Sci-Fi' : 'Science Fiction'}})
# df.loc[df['Movie Name'] == 'Science Friction']  
# df = df.rename(column ={'Genre' : 'Jonor'}})
df['Genre'] = df['Genre'].replace({'Sci-Fi' : 'Science Fiction'})
# print(df['Genre'].str.contains('Science Fiction', case = False, na= False))
print(df['Genre'].head(20).to_list())

['Mystery', 'Drama', 'Adventure', 'Adventure', 'Fantasy', 'Action', 'Horror', 'Thriller', 'Thriller', 'Sci-Fi', 'Fantasy', 'Thriller', 'Drama', 'Drama', 'Mystery', 'Mystery', 'Adventure', 'Comedy', 'Comedy', 'Action']
['Mystery', 'Drama', 'Adventure', 'Adventure', 'Fantasy', 'Action', 'Horror', 'Thriller', 'Thriller', 'Science Fiction', 'Fantasy', 'Thriller', 'Drama', 'Drama', 'Mystery', 'Mystery', 'Adventure', 'Comedy', 'Comedy', 'Action']

In [77]:
# 16. Select the first 10 movies. 
# df=df.sort_values('Rank',ascending =False)
df['Movie Name'].head(10)

157    Movie 158
41      Movie 42
947    Movie 948
324    Movie 325
337    Movie 338
853    Movie 854
283    Movie 284
102    Movie 103
794    Movie 795
170    Movie 171
Name: Movie Name, dtype: str

In [81]:
# 17. Select the last 5 movies.
df['Movie Name'].tail(5)

108    Movie 109
211    Movie 212
153    Movie 154
776    Movie 777
178    Movie 179
Name: Movie Name, dtype: str

In [99]:
# 18. Group movies by genre and find the average IMDb rating for each genre. 
genre_rating = df.groupby('Genre')['IMDb_Rating'].mean()
print(genre_rating)

Genre
Action             5.670192
Adventure          4.982105
Comedy             5.466667
Drama              5.191071
Fantasy            5.183962
Horror             5.810112
Mystery            5.772727
Romance            5.938462
Science Fiction    5.471739
Thriller           5.267290
Name: IMDb_Rating, dtype: float64

In [ ]:
# 19. Find the number of movies released in each year.

In [ ]:
movie_release_year = df.groupby('Release_Year').size()
display(movie_release_year)

In [108]:
# 20. Find the total box office collection per genre.
df.groupby('Genre')['Revenue']sum()

Genre
Action             111137.94
Adventure          102437.69
Comedy             119580.40
Drama              118958.66
Fantasy            108251.78
Horror              89281.21
Mystery             98236.50
Romance             94413.72
Science Fiction     84677.79
Thriller           112412.12
Name: Revenue, dtype: float64

In [ ]:
# value_counts()
# sort_values()